version: '3.9'
services:
  mysql:
    container_name: bootcamp-mysql
    networks:
      bootcamp-web:
    image: mysql:5.7
    command: mysqld --sql_mode=""
    environment:
      MYSQL_DATABASE: 'crm'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql:delegated

  mongodb:
    image: mongo
    container_name: bootcamp-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=crm

  redis:
    image: redis
    container_name: bootcamp-redis
    ports:
      - "6379:6379"

  kibana:
    image: docker.elastic.co/kibana/kibana:5.1.2
    container_name: bootcamp-kibana
    networks:
     bootcamp-web:
    domainname: local.com
    hostname: kibana
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    environment:
          - "ELASTICSEARCH_URL=http://elasticsearch:9200"

  php:
    build:
      context: ./6.crud-php
    networks:
      bootcamp-web:
    container_name: bootcamp-php
    volumes:
      - type: bind
        source: ./6.crud-php
        target: /var/www/html
    ports: 
      - 9991:80
    tty: true
    stdin_open: true


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.1.2
    container_name: bootcamp-elasticsearch
    networks:
      bootcamp-web:
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

networks:
  bootcamp-web:
